import cv2
import numpy as np

class TamperDetector:
    def __init__(self):
        # This is built pluggable so future CNN models can be added cleanly.
        self.plugins = [
            self._run_ela,
            self._run_gradient_analysis
        ]
        
    def analyze(self, image):
        """
        Runs all configured tamper detection plugins and normalizes the output.
        Returns a fusion of regional tampering maps and overall risk score.
        """
        results = []
        visual_regions = []
        total_risk = 0.0
        
        for plugin in self.plugins:
            risk_score, regions = plugin(image)
            total_risk += risk_score
            visual_regions.extend(regions)
            
        final_risk = min(1.0, total_risk / len(self.plugins))
        
        return {
            "tamper_risk": final_risk,
            "tampered_regions": visual_regions
        }

    def _run_ela(self, image):
        """Error Level Analysis (ELA) to find manual interpolations and copy-moves"""
        try:
            # Compress image to induce compression artifacts uniformly
            encode_param = [int(cv2.IMWRITE_JPEG_QUALITY), 90]
            _, encoded = cv2.imencode('.jpg', image, encode_param)
            decoded = cv2.imdecode(encoded, 1)
            
            # Compute difference between original and compressed
            diff = cv2.absdiff(image, decoded)
            
            # Max pooling / scaling
            max_diff = np.amax(diff)
            if max_diff == 0: 
                return 0.0, []
                
            scale = 255.0 / max_diff
            ela_img = cv2.convertScaleAbs(diff, alpha=scale)
            
            # Grayscale & threshold
            gray = cv2.cvtColor(ela_img, cv2.COLOR_BGR2GRAY)
            _, thresh = cv2.threshold(gray, 200, 255, cv2.THRESH_BINARY)
            
            # Find contours
            contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            
            regions = []
            max_area = 0
            for cnt in contours:
                area = cv2.contourArea(cnt)
                if area > 100: # Filter noise
                    x, y, w, h = cv2.boundingRect(cnt)
                    regions.append({
                        "region": "ela_anomaly",
                        "risk": min(1.0, area / 5000.0),
                        "box": [int(x), int(y), int(x+w), int(y+h)],
                        "reason": "Compression artifact variance (splicing)"
                    })
                    max_area = max(max_area, area)
            
            risk_score = min(1.0, len(regions) * 0.1 + (max_area / 10000.0))
            return risk_score, regions
        except Exception:
            return 0.0, []
            
    def _run_gradient_analysis(self, image):
        """Finds sharp unnatural gradient drops generated by edge feathering"""
        try:
            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
            laplacian = cv2.Laplacian(gray, cv2.CV_64F)
            variance = laplacian.var()
            
            if variance < 50:
                return 0.7, [{"region": "blur_anomaly", "risk": 0.7, "box": [0,0, image.shape[1], image.shape[0]], "reason": "Unnaturally blurred layout"}]
            return 0.0, []
        except Exception:
            return 0.0, []
